# DAPR Secret Store for Azure Key Vault
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "kv-backup-api"
  - name: azureClientId
    value: "" # Will be populated by managed identity
  - name: azureTenantId
    value: "" # Will be populated by managed identity
