# Local pub/sub using Redis
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: backup-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: ""
