<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>5ed2dfc4-d949-471e-b756-f5eef4dae4bd</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\common\logging\FlorisDeV.Logging.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.13.1" />
        <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
        <PackageReference Include="OpenTelemetry" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
        <PackageReference Include="Refit" Version="10.0.1" />
        <PackageReference Include="Refit.HttpClientFactory" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include=".backupignore">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
